name: Scraper CI

on:
  push:
    paths:
      - 'scrapers/**'
  pull_request:
    paths:
      - 'scrapers/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        working-directory: scrapers
        run: |
          pip install -r requirements.txt
          
      - name: Run tests
        working-directory: scrapers/tests/
        run: pytest --maxfail=1 --disable-warnings
