name: Scraper CI

on:
  push:
    paths:
      - 'scrapers/**'
  pull_request:
    paths:
      - 'scrapers/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        working-directory: scrapers
        run: |
          pip install -r requirements.txt

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install Geckodriver
        run: |
          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz"
          tar -xzf geckodriver-$GECKO_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          rm geckodriver-$GECKO_VERSION-linux64.tar.gz

      - name: Run tests
        working-directory: scrapers/tests/
        run: pytest --maxfail=1 --disable-warnings
